mdapi/Signup Manager/objects/Signup_Counter__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Index</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Signup Counter</label>
</CustomObject>

mdapi/Signup Manager/classes/SignupHelper.cls
public class SignupHelper 
{
	public static Signup_Counter__c getSignupCounter()
    {
        return Signup_Counter__c.getOrgDefaults();
    }
    
    public static void incrementSignupCounter()
    {
        Signup_Counter__c counter = getSignupCounter();
        setSignupCounter(counter.Index__c+1);
    }
    
    private static void setSignupCounter(decimal index)
    {
        Signup_Counter__c counter = Signup_Counter__c.getOrgDefaults();
        counter.Index__c = index;
        update counter;
    }
    
    public static Id createSignupRequestByEdition(string company, string countryCode, string edition, string email, string firstName, string lastName, string language)
    {
        Signup_Counter__c counter = getSignupCounter();
        
        SignupRequest sr = new SignupRequest
            (
                Company = company,
                Country = countryCode,
                Edition = edition,
                SignupEmail = email,
                FirstName = firstName,
                LastName = lastName,
                PreferredLanguage = language,
                Subdomain = string.format(counter.Domain__c, new List<object> { counter.Index__c }),
                Username = string.format(counter.Username__c, new List<object> { counter.Index__c })
            );
        
        insert sr;
        
        return sr.Id;
    }
    
    public static Id createSignupRequestByTemplateId(string company, string countryCode, string email, string firstName, string lastName, string language, string templateId)
    {
        Signup_Counter__c counter = getSignupCounter();
        
        SignupRequest sr = new SignupRequest
            (
                Company = company,
                Country = countryCode,
                SignupEmail = email,
                FirstName = firstName,
                LastName = lastName,
                PreferredLanguage = language,
                Subdomain = string.format(counter.Domain__c, new List<object> { counter.Index__c }),
                TemplateId = templateId,
                Username = string.format(counter.Username__c, new List<object> { counter.Index__c })
            );
        
        insert sr;
        
        incrementSignupCounter();
        
        return sr.Id;
    }
    
    public static string getSignupRequestStatus(Id signupRequestId)
    {
        List<SignupRequest> srs = [SELECT Id, Status FROM SignupRequest WHERE Id =: signupRequestId];
        
        if(!srs.isEmpty())
        {
            return srs.get(0).Status;
        }
        
        return null;
    }
}